name: iatros_web
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^15.1.2
  supabase_flutter: ^2.10.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.1.2  
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  intl_phone_field: ^3.2.0
  universal_html: ^2.2.4

  easy_localization: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9


flutter:

  uses-material-design: true

  assets:
    - assets/image/logo.png
    - .env

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/static/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/static/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/SourceCodePro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/static/SourceCodePro-Black.ttf
          weight: 900
        - asset: assets/fonts/static/SourceCodePro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/static/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/static/SourceCodePro-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/static/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/static/SourceCodePro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/static/SourceCodePro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/static/SourceCodePro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/static/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
